namespace Expense_Tracker_v2
{
    partial class Category
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Category));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuFormControlBox1 = new Bunifu.UI.WinForms.BunifuFormControlBox();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.category_cat = new Bunifu.UI.WinForms.BunifuTextBox();
            this.category_addBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.category_type = new Bunifu.UI.WinForms.BunifuDropdown();
            this.category_status = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.category_deleteBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.category_clearBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.category_updateBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuFormControlBox1
            // 
            this.bunifuFormControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuFormControlBox1.BunifuFormDrag = null;
            this.bunifuFormControlBox1.CloseBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.CloseBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.CloseBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.CloseBoxOptions.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.CloseBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.CloseBoxOptions.Icon")));
            this.bunifuFormControlBox1.CloseBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.CloseBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.CloseBoxOptions.IconHoverColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconPressedColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconSize = new System.Drawing.Size(18, 18);
            this.bunifuFormControlBox1.CloseBoxOptions.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.HelpBox = false;
            this.bunifuFormControlBox1.HelpBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.HelpBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.HelpBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.HelpBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.HelpBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.HelpBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.HelpBoxOptions.Icon")));
            this.bunifuFormControlBox1.HelpBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.HelpBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconSize = new System.Drawing.Size(22, 22);
            this.bunifuFormControlBox1.HelpBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Location = new System.Drawing.Point(1155, -2);
            this.bunifuFormControlBox1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuFormControlBox1.MaximizeBox = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconAlt = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.IconAlt")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconSize = new System.Drawing.Size(16, 16);
            this.bunifuFormControlBox1.MaximizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.MinimizeBox = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MinimizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconSize = new System.Drawing.Size(14, 14);
            this.bunifuFormControlBox1.MinimizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Name = "bunifuFormControlBox1";
            this.bunifuFormControlBox1.ShowDesignBorders = false;
            this.bunifuFormControlBox1.Size = new System.Drawing.Size(183, 50);
            this.bunifuFormControlBox1.TabIndex = 0;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 10;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel2.Controls.Add(this.bunifuDataGridView1);
            this.bunifuPanel2.Location = new System.Drawing.Point(37, 73);
            this.bunifuPanel2.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(763, 647);
            this.bunifuPanel2.TabIndex = 0;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(55, 32);
            this.bunifuLabel3.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(145, 36);
            this.bunifuLabel3.TabIndex = 17;
            this.bunifuLabel3.Text = "Categories List";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = false;
            this.bunifuDataGridView1.AllowUserToAddRows = false;
            this.bunifuDataGridView1.AllowUserToDeleteRows = false;
            this.bunifuDataGridView1.AllowUserToResizeColumns = false;
            this.bunifuDataGridView1.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(226)))), ((int)(((byte)(199)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.ForestGreen;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(111)))), ((int)(((byte)(27)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridView1.ColumnHeadersHeight = 40;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(226)))), ((int)(((byte)(199)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(185)))), ((int)(((byte)(122)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.ForestGreen;
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(220)))), ((int)(((byte)(188)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.ForestGreen;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(111)))), ((int)(((byte)(27)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(231)))), ((int)(((byte)(210)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(185)))), ((int)(((byte)(122)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(231)))), ((int)(((byte)(210)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(185)))), ((int)(((byte)(122)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(220)))), ((int)(((byte)(188)))));
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.ForestGreen;
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(21, 74);
            this.bunifuDataGridView1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.ReadOnly = true;
            this.bunifuDataGridView1.RowHeadersVisible = false;
            this.bunifuDataGridView1.RowHeadersWidth = 51;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Poppins", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuDataGridView1.RowsDefaultCellStyle = dataGridViewCellStyle4;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.CellSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(721, 553);
            this.bunifuDataGridView1.TabIndex = 0;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.ForestGreen;
            this.bunifuDataGridView1.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.bunifuDataGridView1_CellClick);
            this.bunifuDataGridView1.Scroll += new System.Windows.Forms.ScrollEventHandler(this.bunifuDataGridView1_Scroll);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(39, 32);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(93, 36);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Category";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.Location = new System.Drawing.Point(52, 144);
            this.bunifuLabel4.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(48, 36);
            this.bunifuLabel4.TabIndex = 12;
            this.bunifuLabel4.Text = "Type";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // category_cat
            // 
            this.category_cat.AcceptsReturn = false;
            this.category_cat.AcceptsTab = false;
            this.category_cat.AnimationSpeed = 200;
            this.category_cat.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.category_cat.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.category_cat.AutoSizeHeight = true;
            this.category_cat.BackColor = System.Drawing.Color.Transparent;
            this.category_cat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("category_cat.BackgroundImage")));
            this.category_cat.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.category_cat.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.category_cat.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.category_cat.BorderColorIdle = System.Drawing.Color.Silver;
            this.category_cat.BorderRadius = 20;
            this.category_cat.BorderThickness = 1;
            this.category_cat.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.category_cat.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.category_cat.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.category_cat.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.category_cat.DefaultText = "";
            this.category_cat.FillColor = System.Drawing.Color.White;
            this.category_cat.HideSelection = true;
            this.category_cat.IconLeft = null;
            this.category_cat.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.category_cat.IconPadding = 10;
            this.category_cat.IconRight = null;
            this.category_cat.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.category_cat.Lines = new string[0];
            this.category_cat.Location = new System.Drawing.Point(52, 74);
            this.category_cat.Margin = new System.Windows.Forms.Padding(4);
            this.category_cat.MaxLength = 32767;
            this.category_cat.MinimumSize = new System.Drawing.Size(1, 1);
            this.category_cat.Modified = false;
            this.category_cat.Multiline = false;
            this.category_cat.Name = "category_cat";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.category_cat.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.category_cat.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.category_cat.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.category_cat.OnIdleState = stateProperties4;
            this.category_cat.Padding = new System.Windows.Forms.Padding(4);
            this.category_cat.PasswordChar = '\0';
            this.category_cat.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.category_cat.PlaceholderText = "Enter text";
            this.category_cat.ReadOnly = false;
            this.category_cat.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.category_cat.SelectedText = "";
            this.category_cat.SelectionLength = 0;
            this.category_cat.SelectionStart = 0;
            this.category_cat.ShortcutsEnabled = true;
            this.category_cat.Size = new System.Drawing.Size(373, 48);
            this.category_cat.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.category_cat.TabIndex = 1;
            this.category_cat.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.category_cat.TextMarginBottom = 0;
            this.category_cat.TextMarginLeft = 3;
            this.category_cat.TextMarginTop = 1;
            this.category_cat.TextPlaceholder = "Enter text";
            this.category_cat.UseSystemPasswordChar = false;
            this.category_cat.WordWrap = true;
            this.category_cat.TextChanged += new System.EventHandler(this.category_cat_TextChanged);
            // 
            // category_addBtn
            // 
            this.category_addBtn.AllowAnimations = true;
            this.category_addBtn.AllowMouseEffects = true;
            this.category_addBtn.AllowToggling = false;
            this.category_addBtn.AnimationSpeed = 200;
            this.category_addBtn.AutoGenerateColors = false;
            this.category_addBtn.AutoRoundBorders = false;
            this.category_addBtn.AutoSizeLeftIcon = true;
            this.category_addBtn.AutoSizeRightIcon = true;
            this.category_addBtn.BackColor = System.Drawing.Color.Transparent;
            this.category_addBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_addBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("category_addBtn.BackgroundImage")));
            this.category_addBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_addBtn.ButtonText = "Add";
            this.category_addBtn.ButtonTextMarginLeft = 0;
            this.category_addBtn.ColorContrastOnClick = 45;
            this.category_addBtn.ColorContrastOnHover = 45;
            this.category_addBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.category_addBtn.CustomizableEdges = borderEdges1;
            this.category_addBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.category_addBtn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.category_addBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_addBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.category_addBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.category_addBtn.Font = new System.Drawing.Font("Poppins", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.category_addBtn.ForeColor = System.Drawing.Color.White;
            this.category_addBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.category_addBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.category_addBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.category_addBtn.IconMarginLeft = 11;
            this.category_addBtn.IconPadding = 10;
            this.category_addBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.category_addBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.category_addBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.category_addBtn.IconSize = 25;
            this.category_addBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.category_addBtn.IdleBorderRadius = 30;
            this.category_addBtn.IdleBorderThickness = 1;
            this.category_addBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_addBtn.IdleIconLeftImage = null;
            this.category_addBtn.IdleIconRightImage = null;
            this.category_addBtn.IndicateFocus = false;
            this.category_addBtn.Location = new System.Drawing.Point(52, 391);
            this.category_addBtn.Margin = new System.Windows.Forms.Padding(4);
            this.category_addBtn.Name = "category_addBtn";
            this.category_addBtn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.category_addBtn.OnDisabledState.BorderRadius = 30;
            this.category_addBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_addBtn.OnDisabledState.BorderThickness = 1;
            this.category_addBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_addBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.category_addBtn.OnDisabledState.IconLeftImage = null;
            this.category_addBtn.OnDisabledState.IconRightImage = null;
            this.category_addBtn.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.category_addBtn.onHoverState.BorderRadius = 30;
            this.category_addBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_addBtn.onHoverState.BorderThickness = 1;
            this.category_addBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(164)))), ((int)(((byte)(133)))));
            this.category_addBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.category_addBtn.onHoverState.IconLeftImage = null;
            this.category_addBtn.onHoverState.IconRightImage = null;
            this.category_addBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.category_addBtn.OnIdleState.BorderRadius = 30;
            this.category_addBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_addBtn.OnIdleState.BorderThickness = 1;
            this.category_addBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_addBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.category_addBtn.OnIdleState.IconLeftImage = null;
            this.category_addBtn.OnIdleState.IconRightImage = null;
            this.category_addBtn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.category_addBtn.OnPressedState.BorderRadius = 30;
            this.category_addBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_addBtn.OnPressedState.BorderThickness = 1;
            this.category_addBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(164)))), ((int)(((byte)(133)))));
            this.category_addBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.category_addBtn.OnPressedState.IconLeftImage = null;
            this.category_addBtn.OnPressedState.IconRightImage = null;
            this.category_addBtn.Size = new System.Drawing.Size(161, 57);
            this.category_addBtn.TabIndex = 8;
            this.category_addBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.category_addBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.category_addBtn.TextMarginLeft = 0;
            this.category_addBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.category_addBtn.UseDefaultRadiusAndThickness = true;
            this.category_addBtn.Click += new System.EventHandler(this.category_addBtn_Click);
            // 
            // category_type
            // 
            this.category_type.BackColor = System.Drawing.Color.Transparent;
            this.category_type.BackgroundColor = System.Drawing.Color.White;
            this.category_type.BorderColor = System.Drawing.Color.Silver;
            this.category_type.BorderRadius = 10;
            this.category_type.Color = System.Drawing.Color.Silver;
            this.category_type.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.category_type.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.category_type.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.category_type.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.category_type.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.category_type.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.category_type.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.category_type.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.category_type.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.category_type.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.category_type.FillDropDown = true;
            this.category_type.FillIndicator = false;
            this.category_type.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.category_type.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.category_type.ForeColor = System.Drawing.Color.Black;
            this.category_type.FormattingEnabled = true;
            this.category_type.Icon = null;
            this.category_type.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.category_type.IndicatorColor = System.Drawing.Color.DarkGray;
            this.category_type.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.category_type.IndicatorThickness = 2;
            this.category_type.IsDropdownOpened = false;
            this.category_type.ItemBackColor = System.Drawing.Color.White;
            this.category_type.ItemBorderColor = System.Drawing.Color.White;
            this.category_type.ItemForeColor = System.Drawing.Color.Black;
            this.category_type.ItemHeight = 26;
            this.category_type.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.category_type.ItemHighLightForeColor = System.Drawing.Color.White;
            this.category_type.Items.AddRange(new object[] {
            "Income",
            "Expenses"});
            this.category_type.ItemTopMargin = 3;
            this.category_type.Location = new System.Drawing.Point(52, 186);
            this.category_type.Margin = new System.Windows.Forms.Padding(4);
            this.category_type.Name = "category_type";
            this.category_type.Size = new System.Drawing.Size(373, 32);
            this.category_type.TabIndex = 6;
            this.category_type.Text = null;
            this.category_type.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.category_type.TextLeftMargin = 5;
            // 
            // category_status
            // 
            this.category_status.BackColor = System.Drawing.Color.Transparent;
            this.category_status.BackgroundColor = System.Drawing.Color.White;
            this.category_status.BorderColor = System.Drawing.Color.Silver;
            this.category_status.BorderRadius = 10;
            this.category_status.Color = System.Drawing.Color.Silver;
            this.category_status.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.category_status.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.category_status.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.category_status.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.category_status.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.category_status.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.category_status.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.category_status.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.category_status.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.category_status.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.category_status.FillDropDown = true;
            this.category_status.FillIndicator = false;
            this.category_status.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.category_status.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.category_status.ForeColor = System.Drawing.Color.Black;
            this.category_status.FormattingEnabled = true;
            this.category_status.Icon = null;
            this.category_status.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.category_status.IndicatorColor = System.Drawing.Color.DarkGray;
            this.category_status.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.category_status.IndicatorThickness = 2;
            this.category_status.IsDropdownOpened = false;
            this.category_status.ItemBackColor = System.Drawing.Color.White;
            this.category_status.ItemBorderColor = System.Drawing.Color.White;
            this.category_status.ItemForeColor = System.Drawing.Color.Black;
            this.category_status.ItemHeight = 26;
            this.category_status.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.category_status.ItemHighLightForeColor = System.Drawing.Color.White;
            this.category_status.Items.AddRange(new object[] {
            "Active",
            "Inactive"});
            this.category_status.ItemTopMargin = 3;
            this.category_status.Location = new System.Drawing.Point(52, 288);
            this.category_status.Margin = new System.Windows.Forms.Padding(4);
            this.category_status.Name = "category_status";
            this.category_status.Size = new System.Drawing.Size(372, 32);
            this.category_status.TabIndex = 7;
            this.category_status.Text = null;
            this.category_status.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.category_status.TextLeftMargin = 5;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 10;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.category_deleteBtn);
            this.bunifuPanel1.Controls.Add(this.category_clearBtn);
            this.bunifuPanel1.Controls.Add(this.category_updateBtn);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel4);
            this.bunifuPanel1.Controls.Add(this.category_status);
            this.bunifuPanel1.Controls.Add(this.category_type);
            this.bunifuPanel1.Controls.Add(this.category_addBtn);
            this.bunifuPanel1.Controls.Add(this.category_cat);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Location = new System.Drawing.Point(837, 73);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(467, 647);
            this.bunifuPanel1.TabIndex = 1;
            // 
            // category_deleteBtn
            // 
            this.category_deleteBtn.AllowAnimations = true;
            this.category_deleteBtn.AllowMouseEffects = true;
            this.category_deleteBtn.AllowToggling = false;
            this.category_deleteBtn.AnimationSpeed = 200;
            this.category_deleteBtn.AutoGenerateColors = false;
            this.category_deleteBtn.AutoRoundBorders = false;
            this.category_deleteBtn.AutoSizeLeftIcon = true;
            this.category_deleteBtn.AutoSizeRightIcon = true;
            this.category_deleteBtn.BackColor = System.Drawing.Color.Transparent;
            this.category_deleteBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_deleteBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("category_deleteBtn.BackgroundImage")));
            this.category_deleteBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_deleteBtn.ButtonText = "Delete";
            this.category_deleteBtn.ButtonTextMarginLeft = 0;
            this.category_deleteBtn.ColorContrastOnClick = 45;
            this.category_deleteBtn.ColorContrastOnHover = 45;
            this.category_deleteBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.category_deleteBtn.CustomizableEdges = borderEdges2;
            this.category_deleteBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.category_deleteBtn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.category_deleteBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_deleteBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.category_deleteBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.category_deleteBtn.Font = new System.Drawing.Font("Poppins", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.category_deleteBtn.ForeColor = System.Drawing.Color.White;
            this.category_deleteBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.category_deleteBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.category_deleteBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.category_deleteBtn.IconMarginLeft = 11;
            this.category_deleteBtn.IconPadding = 10;
            this.category_deleteBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.category_deleteBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.category_deleteBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.category_deleteBtn.IconSize = 25;
            this.category_deleteBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.category_deleteBtn.IdleBorderRadius = 30;
            this.category_deleteBtn.IdleBorderThickness = 1;
            this.category_deleteBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_deleteBtn.IdleIconLeftImage = null;
            this.category_deleteBtn.IdleIconRightImage = null;
            this.category_deleteBtn.IndicateFocus = false;
            this.category_deleteBtn.Location = new System.Drawing.Point(264, 489);
            this.category_deleteBtn.Margin = new System.Windows.Forms.Padding(4);
            this.category_deleteBtn.Name = "category_deleteBtn";
            this.category_deleteBtn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.category_deleteBtn.OnDisabledState.BorderRadius = 30;
            this.category_deleteBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_deleteBtn.OnDisabledState.BorderThickness = 1;
            this.category_deleteBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_deleteBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.category_deleteBtn.OnDisabledState.IconLeftImage = null;
            this.category_deleteBtn.OnDisabledState.IconRightImage = null;
            this.category_deleteBtn.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.category_deleteBtn.onHoverState.BorderRadius = 30;
            this.category_deleteBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_deleteBtn.onHoverState.BorderThickness = 1;
            this.category_deleteBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(164)))), ((int)(((byte)(133)))));
            this.category_deleteBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.category_deleteBtn.onHoverState.IconLeftImage = null;
            this.category_deleteBtn.onHoverState.IconRightImage = null;
            this.category_deleteBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.category_deleteBtn.OnIdleState.BorderRadius = 30;
            this.category_deleteBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_deleteBtn.OnIdleState.BorderThickness = 1;
            this.category_deleteBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_deleteBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.category_deleteBtn.OnIdleState.IconLeftImage = null;
            this.category_deleteBtn.OnIdleState.IconRightImage = null;
            this.category_deleteBtn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.category_deleteBtn.OnPressedState.BorderRadius = 30;
            this.category_deleteBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_deleteBtn.OnPressedState.BorderThickness = 1;
            this.category_deleteBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(164)))), ((int)(((byte)(133)))));
            this.category_deleteBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.category_deleteBtn.OnPressedState.IconLeftImage = null;
            this.category_deleteBtn.OnPressedState.IconRightImage = null;
            this.category_deleteBtn.Size = new System.Drawing.Size(161, 57);
            this.category_deleteBtn.TabIndex = 16;
            this.category_deleteBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.category_deleteBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.category_deleteBtn.TextMarginLeft = 0;
            this.category_deleteBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.category_deleteBtn.UseDefaultRadiusAndThickness = true;
            this.category_deleteBtn.Click += new System.EventHandler(this.category_deleteBtn_Click);
            // 
            // category_clearBtn
            // 
            this.category_clearBtn.AllowAnimations = true;
            this.category_clearBtn.AllowMouseEffects = true;
            this.category_clearBtn.AllowToggling = false;
            this.category_clearBtn.AnimationSpeed = 200;
            this.category_clearBtn.AutoGenerateColors = false;
            this.category_clearBtn.AutoRoundBorders = false;
            this.category_clearBtn.AutoSizeLeftIcon = true;
            this.category_clearBtn.AutoSizeRightIcon = true;
            this.category_clearBtn.BackColor = System.Drawing.Color.Transparent;
            this.category_clearBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_clearBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("category_clearBtn.BackgroundImage")));
            this.category_clearBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_clearBtn.ButtonText = "Clear";
            this.category_clearBtn.ButtonTextMarginLeft = 0;
            this.category_clearBtn.ColorContrastOnClick = 45;
            this.category_clearBtn.ColorContrastOnHover = 45;
            this.category_clearBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.category_clearBtn.CustomizableEdges = borderEdges3;
            this.category_clearBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.category_clearBtn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.category_clearBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_clearBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.category_clearBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.category_clearBtn.Font = new System.Drawing.Font("Poppins", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.category_clearBtn.ForeColor = System.Drawing.Color.White;
            this.category_clearBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.category_clearBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.category_clearBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.category_clearBtn.IconMarginLeft = 11;
            this.category_clearBtn.IconPadding = 10;
            this.category_clearBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.category_clearBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.category_clearBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.category_clearBtn.IconSize = 25;
            this.category_clearBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.category_clearBtn.IdleBorderRadius = 30;
            this.category_clearBtn.IdleBorderThickness = 1;
            this.category_clearBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_clearBtn.IdleIconLeftImage = null;
            this.category_clearBtn.IdleIconRightImage = null;
            this.category_clearBtn.IndicateFocus = false;
            this.category_clearBtn.Location = new System.Drawing.Point(52, 489);
            this.category_clearBtn.Margin = new System.Windows.Forms.Padding(4);
            this.category_clearBtn.Name = "category_clearBtn";
            this.category_clearBtn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.category_clearBtn.OnDisabledState.BorderRadius = 30;
            this.category_clearBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_clearBtn.OnDisabledState.BorderThickness = 1;
            this.category_clearBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_clearBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.category_clearBtn.OnDisabledState.IconLeftImage = null;
            this.category_clearBtn.OnDisabledState.IconRightImage = null;
            this.category_clearBtn.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.category_clearBtn.onHoverState.BorderRadius = 30;
            this.category_clearBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_clearBtn.onHoverState.BorderThickness = 1;
            this.category_clearBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(164)))), ((int)(((byte)(133)))));
            this.category_clearBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.category_clearBtn.onHoverState.IconLeftImage = null;
            this.category_clearBtn.onHoverState.IconRightImage = null;
            this.category_clearBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.category_clearBtn.OnIdleState.BorderRadius = 30;
            this.category_clearBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_clearBtn.OnIdleState.BorderThickness = 1;
            this.category_clearBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_clearBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.category_clearBtn.OnIdleState.IconLeftImage = null;
            this.category_clearBtn.OnIdleState.IconRightImage = null;
            this.category_clearBtn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.category_clearBtn.OnPressedState.BorderRadius = 30;
            this.category_clearBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_clearBtn.OnPressedState.BorderThickness = 1;
            this.category_clearBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(164)))), ((int)(((byte)(133)))));
            this.category_clearBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.category_clearBtn.OnPressedState.IconLeftImage = null;
            this.category_clearBtn.OnPressedState.IconRightImage = null;
            this.category_clearBtn.Size = new System.Drawing.Size(161, 57);
            this.category_clearBtn.TabIndex = 15;
            this.category_clearBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.category_clearBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.category_clearBtn.TextMarginLeft = 0;
            this.category_clearBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.category_clearBtn.UseDefaultRadiusAndThickness = true;
            this.category_clearBtn.Click += new System.EventHandler(this.category_clearBtn_Click);
            // 
            // category_updateBtn
            // 
            this.category_updateBtn.AllowAnimations = true;
            this.category_updateBtn.AllowMouseEffects = true;
            this.category_updateBtn.AllowToggling = false;
            this.category_updateBtn.AnimationSpeed = 200;
            this.category_updateBtn.AutoGenerateColors = false;
            this.category_updateBtn.AutoRoundBorders = false;
            this.category_updateBtn.AutoSizeLeftIcon = true;
            this.category_updateBtn.AutoSizeRightIcon = true;
            this.category_updateBtn.BackColor = System.Drawing.Color.Transparent;
            this.category_updateBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_updateBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("category_updateBtn.BackgroundImage")));
            this.category_updateBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_updateBtn.ButtonText = "Update";
            this.category_updateBtn.ButtonTextMarginLeft = 0;
            this.category_updateBtn.ColorContrastOnClick = 45;
            this.category_updateBtn.ColorContrastOnHover = 45;
            this.category_updateBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.category_updateBtn.CustomizableEdges = borderEdges4;
            this.category_updateBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.category_updateBtn.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.category_updateBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_updateBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.category_updateBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.category_updateBtn.Font = new System.Drawing.Font("Poppins", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.category_updateBtn.ForeColor = System.Drawing.Color.White;
            this.category_updateBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.category_updateBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.category_updateBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.category_updateBtn.IconMarginLeft = 11;
            this.category_updateBtn.IconPadding = 10;
            this.category_updateBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.category_updateBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.category_updateBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.category_updateBtn.IconSize = 25;
            this.category_updateBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.category_updateBtn.IdleBorderRadius = 30;
            this.category_updateBtn.IdleBorderThickness = 1;
            this.category_updateBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_updateBtn.IdleIconLeftImage = null;
            this.category_updateBtn.IdleIconRightImage = null;
            this.category_updateBtn.IndicateFocus = false;
            this.category_updateBtn.Location = new System.Drawing.Point(264, 391);
            this.category_updateBtn.Margin = new System.Windows.Forms.Padding(4);
            this.category_updateBtn.Name = "category_updateBtn";
            this.category_updateBtn.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.category_updateBtn.OnDisabledState.BorderRadius = 30;
            this.category_updateBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_updateBtn.OnDisabledState.BorderThickness = 1;
            this.category_updateBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_updateBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.category_updateBtn.OnDisabledState.IconLeftImage = null;
            this.category_updateBtn.OnDisabledState.IconRightImage = null;
            this.category_updateBtn.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.category_updateBtn.onHoverState.BorderRadius = 30;
            this.category_updateBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_updateBtn.onHoverState.BorderThickness = 1;
            this.category_updateBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(164)))), ((int)(((byte)(133)))));
            this.category_updateBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.category_updateBtn.onHoverState.IconLeftImage = null;
            this.category_updateBtn.onHoverState.IconRightImage = null;
            this.category_updateBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.category_updateBtn.OnIdleState.BorderRadius = 30;
            this.category_updateBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_updateBtn.OnIdleState.BorderThickness = 1;
            this.category_updateBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(207)))), ((int)(((byte)(182)))));
            this.category_updateBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.category_updateBtn.OnIdleState.IconLeftImage = null;
            this.category_updateBtn.OnIdleState.IconRightImage = null;
            this.category_updateBtn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.category_updateBtn.OnPressedState.BorderRadius = 30;
            this.category_updateBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.category_updateBtn.OnPressedState.BorderThickness = 1;
            this.category_updateBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(164)))), ((int)(((byte)(133)))));
            this.category_updateBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.category_updateBtn.OnPressedState.IconLeftImage = null;
            this.category_updateBtn.OnPressedState.IconRightImage = null;
            this.category_updateBtn.Size = new System.Drawing.Size(161, 57);
            this.category_updateBtn.TabIndex = 14;
            this.category_updateBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.category_updateBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.category_updateBtn.TextMarginLeft = 0;
            this.category_updateBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.category_updateBtn.UseDefaultRadiusAndThickness = true;
            this.category_updateBtn.Click += new System.EventHandler(this.category_updateBtn_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.Location = new System.Drawing.Point(52, 246);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(63, 36);
            this.bunifuLabel2.TabIndex = 13;
            this.bunifuLabel2.Text = "Status";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Category
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1336, 750);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.bunifuFormControlBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "Category";
            this.Text = "Category";
            this.Load += new System.EventHandler(this.Category_Load);
            this.bunifuPanel2.ResumeLayout(false);
            this.bunifuPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuFormControlBox bunifuFormControlBox1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox category_cat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 category_addBtn;
        private Bunifu.UI.WinForms.BunifuDropdown category_type;
        private Bunifu.UI.WinForms.BunifuDropdown category_status;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 category_updateBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 category_clearBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 category_deleteBtn;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
    }
}